"""change table to use uuid

Revision ID: 52c952c0f8f5
Revises: 0f4e361c5ebc
Create Date: 2025-12-11 12:27:39.841207

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '52c952c0f8f5'
down_revision: Union[str, Sequence[str], None] = '0f4e361c5ebc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('short_urls',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('original_url', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False),
    sa.Column('short_code', sqlmodel.sql.sqltypes.AutoString(length=22), nullable=False),
    sa.Column('visit_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_short_urls_original_url'), 'short_urls', ['original_url'], unique=False)
    op.create_index(op.f('ix_short_urls_short_code'), 'short_urls', ['short_code'], unique=True)
    op.drop_index(op.f('ix_shorturl_original_url'), table_name='shorturl')
    op.drop_index(op.f('ix_shorturl_short_code'), table_name='shorturl')
    op.drop_table('shorturl')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shorturl',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('original_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('short_code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('visit_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('shorturl_pkey'))
    )
    op.create_index(op.f('ix_shorturl_short_code'), 'shorturl', ['short_code'], unique=True)
    op.create_index(op.f('ix_shorturl_original_url'), 'shorturl', ['original_url'], unique=False)
    op.drop_index(op.f('ix_short_urls_short_code'), table_name='short_urls')
    op.drop_index(op.f('ix_short_urls_original_url'), table_name='short_urls')
    op.drop_table('short_urls')
    # ### end Alembic commands ###
